Update patch set 2
Patch Set 2: -Autosubmit

The is clearly due to the lack of the XFRMA_OUTPUT_MARK code:


======================================================================
ERROR: testTunnelModeOutputMarkAttributes (__main__.XfrmOutputMarkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./xfrm_test.py", line 414, in testTunnelModeOutputMarkAttributes
    self.assertEquals(mark, attributes["XFRMA_OUTPUT_MARK"])
KeyError: 'XFRMA_OUTPUT_MARK'


However, the o-mr1-dev version of xfrm_test.py doesn't have this code at all:

$ git show partner/o-mr1-dev:net/test/xfrm_test.py | grep XFRMA_OUTPUT_MARK
$ git show partner/master:net/test/xfrm_test.py | grep XFRMA_OUTPUT_MARK
      self.assertEquals(mark, attributes["XFRMA_OUTPUT_MARK"])
$


and running the tests manually on angler with:

repo init -b m-dev-msm-angler-3.10 && repo sync -j8 -c
./build/build_test.sh -j64

shows no failures.


git.log suggests that we do start off with the current o-mr1-dev revision of kernel/tests:

Initialized u'/buildbot/src/partner-android/m-dev-msm-angler-3.10/kernel/tests'Executed: ['runalarm', '-t', '2700', '/bin/bash', '-c', u'git checkout -f a48bf88cfaf37d39270288c6801be5500f258454'] from /buildbot/src/partner-android/m-dev-msm-angler-3.10/kernel/tests return code 0

Previous HEAD position was 9c2b3e1... Merge "Skip multicast packets in TunTwister" am: 5034ce2928
HEAD is now at a48bf88... Merge "Add tests for cgroup v2 bpf and new helper functions" am: 48901fd8e9
Executed: ['runalarm', '-t', '2700', '/bin/bash', '-c', 'git clean -dxf'] from /buildbot/src/partner-android/m-dev-msm-angler-3.10/kernel/tests return code 0


but then, when we apply this change, we do a merge, and that pulls in all the changes between o-mr1-dev and master :-(


Git fetch succeeded: git fetch https://android-review.googlesource.com/a/kernel/tests 4d0cc9cfe431350d038d869eafeba9865fd422f4Merge made by the 'recursive' strategy.
 OWNERS                          |   1 -
 net/test/forwarding_test.py     |  89 +++++++++--
 net/test/iproute.py             | 131 +++++++++++++---
 net/test/leak_test.py           |  33 ++++
 net/test/multinetwork_base.py   |  35 +++--
 net/test/multinetwork_test.py   |  22 ++-
 net/test/net_test.py            |  10 ++
 net/test/netlink.py             |  15 +-
 net/test/packets.py             |   9 +-
 net/test/parallel_tests.sh      |  18 ++-
 net/test/qtaguid_test.py        |  73 ++++++++-
 net/test/run_net_test.sh        |   2 +-
 net/test/sock_diag.py           |   7 +-
 net/test/sock_diag_test.py      | 114 +++++++++++++-
 net/test/tcp_test.py            |   8 +
 net/test/tun_twister.py         | 214 ++++++++++++++++++++++++++
 net/test/xfrm.py                |  91 ++++++++++-
 net/test/xfrm_algorithm_test.py | 282 ++++++++++++++++++++++++++++++++++
 net/test/xfrm_base.py           | 188 +++++++++++++++++++++++
 net/test/xfrm_test.py           | 294 ++++++++++++++++++++---------------
 net/test/xfrm_tunnel_test.py    | 333 ++++++++++++++++++++++++++++++++++++++++
 21 files changed, 1758 insertions(+), 211 deletions(-)
 create mode 100644 net/test/tun_twister.py
 create mode 100755 net/test/xfrm_algorithm_test.py
 create mode 100644 net/test/xfrm_base.py
 create mode 100755 net/test/xfrm_tunnel_test.py
Executing: ['runalarm', '-t', '600', '/bin/bash', '-c', 'git merge -Xpatience FETCH_HEAD'] from /buildbot/src/partner-android/m-dev-msm-angler-3.10/kernel/tests

Patch-set: 2
Reviewer: Gerrit User 1000835 <1000835@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Autosubmit=0