Revert "net-test: Add kernel test for multicast routing"
This reverts commit e11e0f5182ad5c496260bf080d3c320a7959d693.

Reason for revert:
https://android-build.corp.google.com/test_investigate/?invocationId=I44900010235599375&testResultId=TR81229126224314944

======================================================================
ERROR: testEnable3InterfacesSrcToGroupForwarding (multicast_routing_test.MulticastRoutingTest.testEnable3InterfacesSrcToGroupForwarding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "multicast_routing_test.py", line 65, in setUp
OSError: [Errno 92] Protocol not available

======================================================================
ERROR: testEnableSrcToGroupForwarding (multicast_routing_test.MulticastRoutingTest.testEnableSrcToGroupForwarding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "multicast_routing_test.py", line 65, in setUp
OSError: [Errno 92] Protocol not available

----------------------------------------------------------------------
Ran 655 tests in 166.031s

FAILED (errors=2, skipped=7)

Change-Id: I2daa4fb45c930bed2003722516397e511abe88cf