Update patch set 4
Patch Set 4:

The test failed on android-common-3.18 (and on the Pixel 2 kernel, which is 4.4) with EAGAIN.

I don't know if it passed or failed on 4.9 because it didn't run. It failed in the same way many times in a row on two separate occasions, so it looks like this is due to a difference in kernel behaviour instead of just being a flaky test. Perhaps these older kernels do not send notifications when userspace changes the NUD state of an entry to STALE?

Could you try running this manually on 3.18, 4.4 and 4.9? If the test only passes on newer kernels, then you can just do something like:

   def ChangeRouterNudState(self, version, state):
     router = self._RouterAddress(self.netid, version)
     if state == NUD_PERMANENT:
       macaddr = self.RouterMacAddress(self.netid)
     else:
       macaddr = None
     self.iproute.UpdateNeighbour(version, router, macaddr, self.ifindex, state)
-    self.ExpectNeighbourNotification(router, state)
+    # The kernel only sends this notification in 4.9 and above.
+    if net_test.LINUX_VERSION >= (4, 9, 0):
+      self.ExpectNeighbourNotification(router, state)
     self.assertNeighbourState(state, router)


Also - does this test pass on older kernels if you always do "macaddr = self.RouterMacAddress(self.netid)", instead of making macaddr be None when you set the state to NUD_STALE?


##### ./neighbour_test.py (9/24)

WARNING: No route found for IPv6 destination :: (no default route?)
EEEE
======================================================================
ERROR: testIsRouterFlag (__main__.NeighbourTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./neighbour_test.py", line 99, in setUp
self.ChangeRouterNudState(4, NUD_STALE)
File "./neighbour_test.py", line 120, in ChangeRouterNudState
self.ExpectNeighbourNotification(router, state)
File "./neighbour_test.py", line 142, in ExpectNeighbourNotification
msg = self.sock.recv(4096)
error: [Errno 11] Resource temporarily unavailable

======================================================================
ERROR: testNotifications (__main__.NeighbourTest)
Tests neighbour notifications.
----------------------------------------------------------------------
Traceback (most recent call last):
File "./neighbour_test.py", line 99, in setUp
self.ChangeRouterNudState(4, NUD_STALE)
File "./neighbour_test.py", line 120, in ChangeRouterNudState
self.ExpectNeighbourNotification(router, state)
File "./neighbour_test.py", line 142, in ExpectNeighbourNotification
msg = self.sock.recv(4096)
error: [Errno 11] Resource temporarily unavailable

======================================================================
ERROR: testReconfigureDuringProbing (__main__.NeighbourTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./neighbour_test.py", line 99, in setUp
self.ChangeRouterNudState(4, NUD_STALE)
File "./neighbour_test.py", line 120, in ChangeRouterNudState
self.ExpectNeighbourNotification(router, state)
File "./neighbour_test.py", line 142, in ExpectNeighbourNotification
msg = self.sock.recv(4096)
error: [Errno 11] Resource temporarily unavailable

======================================================================
ERROR: testRepeatedProbes (__main__.NeighbourTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./neighbour_test.py", line 99, in setUp
self.ChangeRouterNudState(4, NUD_STALE)
File "./neighbour_test.py", line 120, in ChangeRouterNudState
self.ExpectNeighbourNotification(router, state)
File "./neighbour_test.py", line 142, in ExpectNeighbourNotification
msg = self.sock.recv(4096)
error: [Errno 11] Resource temporarily unavailable

----------------------------------------------------------------------
Ran 4 tests in 0.274s

FAILED (errors=4)
WARNING: No route found for IPv6 destination :: (no default route?)
EEEE
======================================================================
ERROR: testIsRouterFlag (__main__.NeighbourTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./neighbour_test.py", line 99, in setUp
self.ChangeRouterNudState(4, NUD_STALE)
File "./neighbour_test.py", line 120, in ChangeRouterNudState
self.ExpectNeighbourNotification(router, state)
File "./neighbour_test.py", line 142, in ExpectNeighbourNotification
msg = self.sock.recv(4096)
error: [Errno 11] Resource temporarily unavailable

======================================================================
ERROR: testNotifications (__main__.NeighbourTest)
Tests neighbour notifications.
----------------------------------------------------------------------
Traceback (most recent call last):
File "./neighbour_test.py", line 99, in setUp
self.ChangeRouterNudState(4, NUD_STALE)
File "./neighbour_test.py", line 120, in ChangeRouterNudState
self.ExpectNeighbourNotification(router, state)
File "./neighbour_test.py", line 142, in ExpectNeighbourNotification
msg = self.sock.recv(4096)
error: [Errno 11] Resource temporarily unavailable

======================================================================
ERROR: testReconfigureDuringProbing (__main__.NeighbourTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./neighbour_test.py", line 99, in setUp
self.ChangeRouterNudState(4, NUD_STALE)
File "./neighbour_test.py", line 120, in ChangeRouterNudState
self.ExpectNeighbourNotification(router, state)
File "./neighbour_test.py", line 142, in ExpectNeighbourNotification
msg = self.sock.recv(4096)
error: [Errno 11] Resource temporarily unavailable

======================================================================
ERROR: testRepeatedProbes (__main__.NeighbourTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "./neighbour_test.py", line 99, in setUp
self.ChangeRouterNudState(4, NUD_STALE)
File "./neighbour_test.py", line 120, in ChangeRouterNudState
self.ExpectNeighbourNotification(router, state)
File "./neighbour_test.py", line 142, in ExpectNeighbourNotification
msg = self.sock.recv(4096)
error: [Errno 11] Resource temporarily unavailable

----------------------------------------------------------------------
Ran 4 tests in 0.286s

FAILED (errors=4)
'./neighbour_test.py' failed more than once, giving up

Patch-set: 4
Reviewer: Gerrit User 1000835 <1000835@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0