Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> The test failed on android-common-3.18 (and on the Pixel 2 kernel, which is 4.4) with EAGAIN.
> 
> I don't know if it passed or failed on 4.9 because it didn't run. It failed in the same way many times in a row on two separate occasions, so it looks like this is due to a difference in kernel behaviour instead of just being a flaky test. Perhaps these older kernels do not send notifications when userspace changes the NUD state of an entry to STALE?
> 
> Could you try running this manually on 3.18, 4.4 and 4.9? If the test only passes on newer kernels, then you can just do something like:
> 
>    def ChangeRouterNudState(self, version, state):
>      router = self._RouterAddress(self.netid, version)
>      if state == NUD_PERMANENT:
>        macaddr = self.RouterMacAddress(self.netid)
>      else:
>        macaddr = None
>      self.iproute.UpdateNeighbour(version, router, macaddr, self.ifindex, state)
> -    self.ExpectNeighbourNotification(router, state)
> +    # The kernel only sends this notification in 4.9 and above.
> +    if net_test.LINUX_VERSION >= (4, 9, 0):
> +      self.ExpectNeighbourNotification(router, state)
>      self.assertNeighbourState(state, router)
> 
> 
> Also - does this test pass on older kernels if you always do "macaddr = self.RouterMacAddress(self.netid)", instead of making macaddr be None when you set the state to NUD_STALE?
> 
> 
> ##### ./neighbour_test.py (9/24)
> 
> WARNING: No route found for IPv6 destination :: (no default route?)
> EEEE
> ======================================================================
> ERROR: testIsRouterFlag (__main__.NeighbourTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
> File "./neighbour_test.py", line 99, in setUp
> self.ChangeRouterNudState(4, NUD_STALE)
> File "./neighbour_test.py", line 120, in ChangeRouterNudState
> self.ExpectNeighbourNotification(router, state)
> File "./neighbour_test.py", line 142, in ExpectNeighbourNotification
> msg = self.sock.recv(4096)
> error: [Errno 11] Resource temporarily unavailable
> 
> ======================================================================
> ERROR: testNotifications (__main__.NeighbourTest)
> Tests neighbour notifications.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
> File "./neighbour_test.py", line 99, in setUp
> self.ChangeRouterNudState(4, NUD_STALE)
> File "./neighbour_test.py", line 120, in ChangeRouterNudState
> self.ExpectNeighbourNotification(router, state)
> File "./neighbour_test.py", line 142, in ExpectNeighbourNotification
> msg = self.sock.recv(4096)
> error: [Errno 11] Resource temporarily unavailable
> 
> ======================================================================
> ERROR: testReconfigureDuringProbing (__main__.NeighbourTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
> File "./neighbour_test.py", line 99, in setUp
> self.ChangeRouterNudState(4, NUD_STALE)
> File "./neighbour_test.py", line 120, in ChangeRouterNudState
> self.ExpectNeighbourNotification(router, state)
> File "./neighbour_test.py", line 142, in ExpectNeighbourNotification
> msg = self.sock.recv(4096)
> error: [Errno 11] Resource temporarily unavailable
> 
> ======================================================================
> ERROR: testRepeatedProbes (__main__.NeighbourTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
> File "./neighbour_test.py", line 99, in setUp
> self.ChangeRouterNudState(4, NUD_STALE)
> File "./neighbour_test.py", line 120, in ChangeRouterNudState
> self.ExpectNeighbourNotification(router, state)
> File "./neighbour_test.py", line 142, in ExpectNeighbourNotification
> msg = self.sock.recv(4096)
> error: [Errno 11] Resource temporarily unavailable
> 
> ----------------------------------------------------------------------
> Ran 4 tests in 0.274s
> 
> FAILED (errors=4)
> WARNING: No route found for IPv6 destination :: (no default route?)
> EEEE
> ======================================================================
> ERROR: testIsRouterFlag (__main__.NeighbourTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
> File "./neighbour_test.py", line 99, in setUp
> self.ChangeRouterNudState(4, NUD_STALE)
> File "./neighbour_test.py", line 120, in ChangeRouterNudState
> self.ExpectNeighbourNotification(router, state)
> File "./neighbour_test.py", line 142, in ExpectNeighbourNotification
> msg = self.sock.recv(4096)
> error: [Errno 11] Resource temporarily unavailable
> 
> ======================================================================
> ERROR: testNotifications (__main__.NeighbourTest)
> Tests neighbour notifications.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
> File "./neighbour_test.py", line 99, in setUp
> self.ChangeRouterNudState(4, NUD_STALE)
> File "./neighbour_test.py", line 120, in ChangeRouterNudState
> self.ExpectNeighbourNotification(router, state)
> File "./neighbour_test.py", line 142, in ExpectNeighbourNotification
> msg = self.sock.recv(4096)
> error: [Errno 11] Resource temporarily unavailable
> 
> ======================================================================
> ERROR: testReconfigureDuringProbing (__main__.NeighbourTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
> File "./neighbour_test.py", line 99, in setUp
> self.ChangeRouterNudState(4, NUD_STALE)
> File "./neighbour_test.py", line 120, in ChangeRouterNudState
> self.ExpectNeighbourNotification(router, state)
> File "./neighbour_test.py", line 142, in ExpectNeighbourNotification
> msg = self.sock.recv(4096)
> error: [Errno 11] Resource temporarily unavailable
> 
> ======================================================================
> ERROR: testRepeatedProbes (__main__.NeighbourTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
> File "./neighbour_test.py", line 99, in setUp
> self.ChangeRouterNudState(4, NUD_STALE)
> File "./neighbour_test.py", line 120, in ChangeRouterNudState
> self.ExpectNeighbourNotification(router, state)
> File "./neighbour_test.py", line 142, in ExpectNeighbourNotification
> msg = self.sock.recv(4096)
> error: [Errno 11] Resource temporarily unavailable
> 
> ----------------------------------------------------------------------
> Ran 4 tests in 0.286s
> 
> FAILED (errors=4)
> './neighbour_test.py' failed more than once, giving up

hi, Lorenzo
I find that the root cause is in some old kernel versions, the NUD state is not able to change from permanent to stale directly, i'll upload my solution later after all kernel version be verified.

But i find that testNotifications is always fail on kernel-3.18 even with the original version case.
it seems that this case could not pass the test on 3.18, the error message is as follows, have you encountered the same problem？
======================================================================
FAIL: testNotifications (neighbour_test.NeighbourTest)
Tests neighbour notifications.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/kernel_net_tests/neighbour_test.py", line 238, in testNotifications
    self.assertNeighbourAttr(router6, "NDA_PROBES", 2)
  File "/data/kernel_net_tests/neighbour_test.py", line 106, in assertNeighbourAttr
    self.assertEquals(value, self.GetNdEntry(addr)[1][name])
AssertionError: 2 != 3

Patch-set: 4